### ISSUE TITLE
Provide example for Kafka authentication 

### ISSUE THREAD

**Issue by lcmgh** [SeaQL/sea-streamer#5]
Hi!

My credentials/identifiers are like this and I wonder how to pass such credentials to the Kafka crate. I could not find such options in the docs.

```
ssl.endpoint.identification.algorithm=https
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="{{ CLUSTER_API_KEY }}" password="{{ CLUSTER_API_SECRET }}";
```

Could you please outline how to connect with such config attributes?

Thank you!

**Comment by tyt2y3** [comment]
See https://github.com/SeaQL/sea-streamer/pull/4#issuecomment-1523383228

**Comment by hgzimmerman** [comment]
I recall that the core C++ library that the rdkafka rust crate binds to (this crate uses rdkafka) doesn't support jaas: https://github.com/confluentinc/librdkafka/issues/4119

I ran into this when I tried to setup auth myself, and the suggestion provided worked for me, with the code provided https://github.com/SeaQL/sea-streamer/pull/4#issuecomment-1523383228 working for me. That said, my connection string is some long string that looks like `Endpoint=sb://<host>/;SharedAccessKeyName=<keyname>;SharedAccessKey=<secret>`, so that may not work for your needs.
